# Generated by Django 3.2.4 on 2021-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_video_thumb_nail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumb_nail',
        ),
    ]
