# Generated by Django 3.2.4 on 2021-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_remove_video_thumb_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb_nail',
            field=models.FileField(default='a', upload_to='static/'),
            preserve_default=False,
        ),
    ]
